{"name": "test_login_1_wrongData[data2]", "status": "passed", "parameters": [{"name": "data", "value": "{'user': '1868472055', 'pwd': 'python', 'check': '请输入正确的手机号'}"}], "start": 1605453070682, "stop": 1605453071291, "uuid": "150797c4-0af2-4a0e-b171-4e41a5b08728", "historyId": "8ac70931b77eef75755c7acd1436d7ba", "testCaseId": "b94e72c13bb908bf40f210146f458cc0", "fullName": "TestCases.test_login_pytest_fixture.TestLogin#test_login_1_wrongData", "labels": [{"name": "tag", "value": "demo"}, {"name": "tag", "value": "@pytest.mark.usefixtures('refresh')"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login_pytest_fixture"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-9BNRIPUH"}, {"name": "thread", "value": "18836-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login_pytest_fixture"}]}